version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Expose the Next.js app on port 3000
    env_file:
      - .env  # Reference the .env file for sensitive data like MongoDB URI
