version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Expose port 3000 to the outside
    env_file:
      - .env  # Load environment variables if needed
