version: '3.8'
services:
  nextjs-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_DB_URI=${MONGO_DB_URI}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge